/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApiKey = IDL.Record({
  'status' : IDL.Variant({ 'active' : IDL.Null, 'revoked' : IDL.Null }),
  'createdDate' : IDL.Int,
  'keyValue' : IDL.Text,
  'keyName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'accountSID' : IDL.Text,
  'authToken' : IDL.Text,
  'displayName' : IDL.Text,
  'creditBalance' : IDL.Nat,
});
export const DashboardKPIs = IDL.Record({
  'totalMessages' : IDL.Nat,
  'uptime' : IDL.Nat,
  'creditBalance' : IDL.Nat,
  'totalApiCalls' : IDL.Nat,
});
export const ApiLog = IDL.Record({
  'id' : IDL.Text,
  'method' : IDL.Text,
  'endpoint' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'statusCode' : IDL.Nat,
  'durationMs' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : IDL.Variant({
    'topup' : IDL.Null,
    'deduction' : IDL.Null,
  }),
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const UsageRecord = IDL.Record({
  'serviceType' : IDL.Variant({
    'sms' : IDL.Null,
    'voice' : IDL.Null,
    'whatsapp' : IDL.Null,
    'email' : IDL.Null,
  }),
  'cost' : IDL.Nat,
  'date' : IDL.Int,
  'count' : IDL.Nat,
});
export const AvailableNumber = IDL.Record({
  'id' : IDL.Text,
  'country' : IDL.Text,
  'numberType' : IDL.Variant({ 'sms' : IDL.Null, 'voice' : IDL.Null }),
  'number' : IDL.Text,
  'monthlyCost' : IDL.Nat,
});
export const OwnedNumber = IDL.Record({
  'id' : IDL.Text,
  'country' : IDL.Text,
  'purchasedDate' : IDL.Int,
  'numberType' : IDL.Variant({ 'sms' : IDL.Null, 'voice' : IDL.Null }),
  'number' : IDL.Text,
  'monthlyCost' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAvailableNumber' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'sms' : IDL.Null, 'voice' : IDL.Null }),
        IDL.Nat,
      ],
      [],
      [],
    ),
  'addCredits' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'countUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'generateApiKey' : IDL.Func([IDL.Text], [ApiKey], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardKPIs' : IDL.Func([], [DashboardKPIs], ['query']),
  'getLogs' : IDL.Func([], [IDL.Vec(ApiLog)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUsageStats' : IDL.Func([], [IDL.Vec(UsageRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'listApiKeys' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
  'listAvailableNumbers' : IDL.Func([], [IDL.Vec(AvailableNumber)], ['query']),
  'listMyNumbers' : IDL.Func([], [IDL.Vec(OwnedNumber)], ['query']),
  'purchaseNumber' : IDL.Func([IDL.Text], [], []),
  'revokeApiKey' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProfile' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApiKey = IDL.Record({
    'status' : IDL.Variant({ 'active' : IDL.Null, 'revoked' : IDL.Null }),
    'createdDate' : IDL.Int,
    'keyValue' : IDL.Text,
    'keyName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'accountSID' : IDL.Text,
    'authToken' : IDL.Text,
    'displayName' : IDL.Text,
    'creditBalance' : IDL.Nat,
  });
  const DashboardKPIs = IDL.Record({
    'totalMessages' : IDL.Nat,
    'uptime' : IDL.Nat,
    'creditBalance' : IDL.Nat,
    'totalApiCalls' : IDL.Nat,
  });
  const ApiLog = IDL.Record({
    'id' : IDL.Text,
    'method' : IDL.Text,
    'endpoint' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'statusCode' : IDL.Nat,
    'durationMs' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : IDL.Variant({
      'topup' : IDL.Null,
      'deduction' : IDL.Null,
    }),
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const UsageRecord = IDL.Record({
    'serviceType' : IDL.Variant({
      'sms' : IDL.Null,
      'voice' : IDL.Null,
      'whatsapp' : IDL.Null,
      'email' : IDL.Null,
    }),
    'cost' : IDL.Nat,
    'date' : IDL.Int,
    'count' : IDL.Nat,
  });
  const AvailableNumber = IDL.Record({
    'id' : IDL.Text,
    'country' : IDL.Text,
    'numberType' : IDL.Variant({ 'sms' : IDL.Null, 'voice' : IDL.Null }),
    'number' : IDL.Text,
    'monthlyCost' : IDL.Nat,
  });
  const OwnedNumber = IDL.Record({
    'id' : IDL.Text,
    'country' : IDL.Text,
    'purchasedDate' : IDL.Int,
    'numberType' : IDL.Variant({ 'sms' : IDL.Null, 'voice' : IDL.Null }),
    'number' : IDL.Text,
    'monthlyCost' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAvailableNumber' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'sms' : IDL.Null, 'voice' : IDL.Null }),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'addCredits' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'countUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'generateApiKey' : IDL.Func([IDL.Text], [ApiKey], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardKPIs' : IDL.Func([], [DashboardKPIs], ['query']),
    'getLogs' : IDL.Func([], [IDL.Vec(ApiLog)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUsageStats' : IDL.Func([], [IDL.Vec(UsageRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'listApiKeys' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
    'listAvailableNumbers' : IDL.Func(
        [],
        [IDL.Vec(AvailableNumber)],
        ['query'],
      ),
    'listMyNumbers' : IDL.Func([], [IDL.Vec(OwnedNumber)], ['query']),
    'purchaseNumber' : IDL.Func([IDL.Text], [], []),
    'revokeApiKey' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProfile' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };