/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApiKey {
  'status' : { 'active' : null } |
    { 'revoked' : null },
  'createdDate' : bigint,
  'keyValue' : string,
  'keyName' : string,
}
export interface ApiLog {
  'id' : string,
  'method' : string,
  'endpoint' : string,
  'userId' : Principal,
  'timestamp' : bigint,
  'statusCode' : bigint,
  'durationMs' : bigint,
}
export interface AvailableNumber {
  'id' : string,
  'country' : string,
  'numberType' : { 'sms' : null } |
    { 'voice' : null },
  'number' : string,
  'monthlyCost' : bigint,
}
export interface DashboardKPIs {
  'totalMessages' : bigint,
  'uptime' : bigint,
  'creditBalance' : bigint,
  'totalApiCalls' : bigint,
}
export interface OwnedNumber {
  'id' : string,
  'country' : string,
  'purchasedDate' : bigint,
  'numberType' : { 'sms' : null } |
    { 'voice' : null },
  'number' : string,
  'monthlyCost' : bigint,
}
export interface Transaction {
  'id' : string,
  'transactionType' : { 'topup' : null } |
    { 'deduction' : null },
  'description' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface UsageRecord {
  'serviceType' : { 'sms' : null } |
    { 'voice' : null } |
    { 'whatsapp' : null } |
    { 'email' : null },
  'cost' : bigint,
  'date' : bigint,
  'count' : bigint,
}
export interface UserProfile {
  'accountSID' : string,
  'authToken' : string,
  'displayName' : string,
  'creditBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAvailableNumber' : ActorMethod<
    [string, string, string, { 'sms' : null } | { 'voice' : null }, bigint],
    undefined
  >,
  'addCredits' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'countUsers' : ActorMethod<[], bigint>,
  'generateApiKey' : ActorMethod<[string], ApiKey>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardKPIs' : ActorMethod<[], DashboardKPIs>,
  'getLogs' : ActorMethod<[], Array<ApiLog>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUsageStats' : ActorMethod<[], Array<UsageRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'listApiKeys' : ActorMethod<[], Array<ApiKey>>,
  'listAvailableNumbers' : ActorMethod<[], Array<AvailableNumber>>,
  'listMyNumbers' : ActorMethod<[], Array<OwnedNumber>>,
  'purchaseNumber' : ActorMethod<[string], undefined>,
  'revokeApiKey' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProfile' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];