/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ApiKey {
    status: Variant_active_revoked;
    createdDate: bigint;
    keyValue: string;
    keyName: string;
}
export interface AvailableNumber {
    id: string;
    country: string;
    numberType: Variant_sms_voice;
    number: string;
    monthlyCost: bigint;
}
export interface ApiLog {
    id: string;
    method: string;
    endpoint: string;
    userId: Principal;
    timestamp: bigint;
    statusCode: bigint;
    durationMs: bigint;
}
export interface UsageRecord {
    serviceType: Variant_sms_voice_whatsapp_email;
    cost: bigint;
    date: bigint;
    count: bigint;
}
export interface OwnedNumber {
    id: string;
    country: string;
    purchasedDate: bigint;
    numberType: Variant_sms_voice;
    number: string;
    monthlyCost: bigint;
}
export interface DashboardKPIs {
    totalMessages: bigint;
    uptime: bigint;
    creditBalance: bigint;
    totalApiCalls: bigint;
}
export interface UserProfile {
    accountSID: string;
    authToken: string;
    displayName: string;
    creditBalance: bigint;
}
export interface Transaction {
    id: string;
    transactionType: Variant_topup_deduction;
    description: string;
    timestamp: bigint;
    amount: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_revoked {
    active = "active",
    revoked = "revoked"
}
export enum Variant_sms_voice {
    sms = "sms",
    voice = "voice"
}
export enum Variant_sms_voice_whatsapp_email {
    sms = "sms",
    voice = "voice",
    whatsapp = "whatsapp",
    email = "email"
}
export enum Variant_topup_deduction {
    topup = "topup",
    deduction = "deduction"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAvailableNumber(id: string, country: string, number: string, numberType: Variant_sms_voice, monthlyCost: bigint): Promise<void>;
    addCredits(amount: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    countUsers(): Promise<bigint>;
    generateApiKey(keyName: string): Promise<ApiKey>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardKPIs(): Promise<DashboardKPIs>;
    getLogs(): Promise<Array<ApiLog>>;
    getTransactions(): Promise<Array<Transaction>>;
    getUsageStats(): Promise<Array<UsageRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isRegistered(): Promise<boolean>;
    listApiKeys(): Promise<Array<ApiKey>>;
    listAvailableNumbers(): Promise<Array<AvailableNumber>>;
    listMyNumbers(): Promise<Array<OwnedNumber>>;
    purchaseNumber(numberId: string): Promise<void>;
    revokeApiKey(keyValue: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateProfile(displayName: string): Promise<void>;
}
import type { ApiKey as _ApiKey, AvailableNumber as _AvailableNumber, OwnedNumber as _OwnedNumber, Transaction as _Transaction, UsageRecord as _UsageRecord, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAvailableNumber(arg0: string, arg1: string, arg2: string, arg3: Variant_sms_voice, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAvailableNumber(arg0, arg1, arg2, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAvailableNumber(arg0, arg1, arg2, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async addCredits(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCredits(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCredits(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async countUsers(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.countUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countUsers();
            return result;
        }
    }
    async generateApiKey(arg0: string): Promise<ApiKey> {
        if (this.processError) {
            try {
                const result = await this.actor.generateApiKey(arg0);
                return from_candid_ApiKey_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateApiKey(arg0);
            return from_candid_ApiKey_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardKPIs(): Promise<DashboardKPIs> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardKPIs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardKPIs();
            return result;
        }
    }
    async getLogs(): Promise<Array<ApiLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogs();
            return result;
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsageStats(): Promise<Array<UsageRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsageStats();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsageStats();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRegistered();
            return result;
        }
    }
    async listApiKeys(): Promise<Array<ApiKey>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApiKeys();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApiKeys();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAvailableNumbers(): Promise<Array<AvailableNumber>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAvailableNumbers();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAvailableNumbers();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyNumbers(): Promise<Array<OwnedNumber>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyNumbers();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyNumbers();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchaseNumber(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseNumber(arg0);
            return result;
        }
    }
    async revokeApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeApiKey(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return result;
        }
    }
}
function from_candid_ApiKey_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiKey): ApiKey {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_AvailableNumber_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvailableNumber): AvailableNumber {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_OwnedNumber_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OwnedNumber): OwnedNumber {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UsageRecord_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UsageRecord): UsageRecord {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    transactionType: {
        topup: null;
    } | {
        deduction: null;
    };
    description: string;
    timestamp: bigint;
    amount: bigint;
}): {
    id: string;
    transactionType: Variant_topup_deduction;
    description: string;
    timestamp: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: from_candid_variant_n13(_uploadFile, _downloadFile, value.transactionType),
        description: value.description,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: {
        sms: null;
    } | {
        voice: null;
    } | {
        whatsapp: null;
    } | {
        email: null;
    };
    cost: bigint;
    date: bigint;
    count: bigint;
}): {
    serviceType: Variant_sms_voice_whatsapp_email;
    cost: bigint;
    date: bigint;
    count: bigint;
} {
    return {
        serviceType: from_candid_variant_n17(_uploadFile, _downloadFile, value.serviceType),
        cost: value.cost,
        date: value.date,
        count: value.count
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    country: string;
    numberType: {
        sms: null;
    } | {
        voice: null;
    };
    number: string;
    monthlyCost: bigint;
}): {
    id: string;
    country: string;
    numberType: Variant_sms_voice;
    number: string;
    monthlyCost: bigint;
} {
    return {
        id: value.id,
        country: value.country,
        numberType: from_candid_variant_n22(_uploadFile, _downloadFile, value.numberType),
        number: value.number,
        monthlyCost: value.monthlyCost
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    country: string;
    purchasedDate: bigint;
    numberType: {
        sms: null;
    } | {
        voice: null;
    };
    number: string;
    monthlyCost: bigint;
}): {
    id: string;
    country: string;
    purchasedDate: bigint;
    numberType: Variant_sms_voice;
    number: string;
    monthlyCost: bigint;
} {
    return {
        id: value.id,
        country: value.country,
        purchasedDate: value.purchasedDate,
        numberType: from_candid_variant_n22(_uploadFile, _downloadFile, value.numberType),
        number: value.number,
        monthlyCost: value.monthlyCost
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        active: null;
    } | {
        revoked: null;
    };
    createdDate: bigint;
    keyValue: string;
    keyName: string;
}): {
    status: Variant_active_revoked;
    createdDate: bigint;
    keyValue: string;
    keyName: string;
} {
    return {
        status: from_candid_variant_n6(_uploadFile, _downloadFile, value.status),
        createdDate: value.createdDate,
        keyValue: value.keyValue,
        keyName: value.keyName
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topup: null;
} | {
    deduction: null;
}): Variant_topup_deduction {
    return "topup" in value ? Variant_topup_deduction.topup : "deduction" in value ? Variant_topup_deduction.deduction : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sms: null;
} | {
    voice: null;
} | {
    whatsapp: null;
} | {
    email: null;
}): Variant_sms_voice_whatsapp_email {
    return "sms" in value ? Variant_sms_voice_whatsapp_email.sms : "voice" in value ? Variant_sms_voice_whatsapp_email.voice : "whatsapp" in value ? Variant_sms_voice_whatsapp_email.whatsapp : "email" in value ? Variant_sms_voice_whatsapp_email.email : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sms: null;
} | {
    voice: null;
}): Variant_sms_voice {
    return "sms" in value ? Variant_sms_voice.sms : "voice" in value ? Variant_sms_voice.voice : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    revoked: null;
}): Variant_active_revoked {
    return "active" in value ? Variant_active_revoked.active : "revoked" in value ? Variant_active_revoked.revoked : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UsageRecord>): Array<UsageRecord> {
    return value.map((x)=>from_candid_UsageRecord_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApiKey>): Array<ApiKey> {
    return value.map((x)=>from_candid_ApiKey_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AvailableNumber>): Array<AvailableNumber> {
    return value.map((x)=>from_candid_AvailableNumber_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OwnedNumber>): Array<OwnedNumber> {
    return value.map((x)=>from_candid_OwnedNumber_n24(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_sms_voice): {
    sms: null;
} | {
    voice: null;
} {
    return value == Variant_sms_voice.sms ? {
        sms: null
    } : value == Variant_sms_voice.voice ? {
        voice: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
